spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/spadda}
    username: ${SPRING_DATASOURCE_USERNAME:spadda}
    password: ${SPRING_DATASOURCE_PASSWORD:spadda}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

server:
  port: ${PORT:${SERVER_PORT:8080}}
  address: 0.0.0.0
